name: Daily

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm i
    - name: Adjust LLC Taxes
      run: node adjust_llc_taxes.js
    - name: Adjust home value
      run: |
        home_value=$(node get_home_value.js ${{ secrets.HOME_URL }})
        echo $home_value
        node adjust_ynab_account.js Home $home_value
