name: Daily

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm i
    - name: Adjust LLC Taxes
      run: node adjust_llc_taxes.ts ${{ secrets.YNAB_ACCESS_TOKEN }}
    - name: Adjust mortgage
      run: |
        mortgage_value=$(node get_mortgage_balance.ts)
        echo $mortgage_value
        node adjust_ynab_account.ts ${{ secrets.YNAB_ACCESS_TOKEN }} CX-3 $mortgage_value
      env:
        MORTGAGE_USERNAME: ${{ secrets.MORTGAGE_USERNAME }}
        MORTGAGE_PASSWORD: ${{ secrets.MORTGAGE_PASSWORD }}
        QUESTION_1: "${{ secrets.QUESTON_1 }}"
        ANSWER_1: ${{ secrets.ANSWER_1 }}
        QUESTION_2: "${{ secrets.QUESTON_2 }}"
        ANSWER_2: ${{ secrets.ANSWER_2 }}
        QUESTION_3: "${{ secrets.QUESTON_3 }}"
        ANSWER_3: ${{ secrets.ANSWER_3 }}
        QUESTION_4: "${{ secrets.QUESTON_4 }}"
        ANSWER_4: ${{ secrets.ANSWER_4 }}
    - name: Adjust home value
      run: |
        home_value=$(node get_home_value.ts ${{ secrets.URL }})
        echo $home_value
        node adjust_ynab_account.ts ${{ secrets.YNAB_ACCESS_TOKEN }} CX-3 $home_value
