name: Daily

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    - name: Setup Node Environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm i
    - uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        path: video/*
