name: Daily

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    - name: Setup Node Environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm i
    - name: Adjust LLC Taxes
      run: node adjust_llc_taxes.js
    - name: Adjust home value
      run: |
        home_value=$(node get_home_value.js)
        echo $home_value
        node adjust_ynab_account.js Home $home_value
      env:
        HOME_URL: ${{ secrets.HOME_URL }})
    - uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        path: video/*
