name: Property Taxes

on:
  schedule:
  # Jan 1
  - cron: '0 0 1 1 *'
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL_ADDRESS }}
      HERSCHS_PASSWORD: ${{ secrets.HERSCHS_PASSWORD }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm i
    - name: Pay property tax
      run: node pay_lawn_service.js
    - uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        path: video/*
