name: Monthly

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

env:
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm i
    - name: Adjust Corgibytes benefit
      run: node adjust_cb_benefit.ts ${{ secrets.YNAB_ACCESS_TOKEN }}
    - name: Adjust CX-3 value
      run: |
        car1_value=$(node get_car_value.ts ${{ secrets.CAR_API_KEY }} ${{ secrets.VIN1 }})
        echo $car1_value
        node adjust_ynab_account.ts ${{ secrets.YNAB_ACCESS_TOKEN }} CX-3 $car1_value
    - name: Adjust Stelvio value
      run: |
        car2_value=$(node get_car_value.ts ${{ secrets.CAR_API_KEY }} ${{ secrets.VIN2 }})
        echo $car2_value
        node adjust_ynab_account.ts ${{ secrets.YNAB_ACCESS_TOKEN }} Stelvio $car2_value
