name: Monthly

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
      ZOHO_CLIENT_ID: ${{ secrets.ZOHO_CLIENT_ID }}
      ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
      ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: |
        npm i
        npx playwright install
    - name: Adjust home value
      run: |
        home_value=$(node get_home_value.js)
        echo $home_value
        node adjust_ynab_account.js Home $home_value
    - name: Adjust CX-3 value
      run: |
        car1_value=$(node get_car_value.js ${{ secrets.CAR_API_KEY }} ${{ secrets.VIN1 }})
        echo $car1_value
        node adjust_ynab_account.js CX-3 $car1_value
    # TODO: Convert this to CX-5
    # - name: Adjust Stelvio value
    #   run: |
    #     car2_value=$(node get_car_value.js ${{ secrets.CAR_API_KEY }} ${{ secrets.VIN2 }})
    #     echo $car2_value
    #     node adjust_ynab_account.js Stelvio $car2_value
    - name: Send invoice
      run: |
        node send_invoice.js
