name: Monthly

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
      ZOHO_CLIENT_ID: ${{ secrets.ZOHO_CLIENT_ID }}
      ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
      ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Get CX-3 value
      run: |
        car1_value=$(node get_car_value.js ${{ secrets.CAR_API_KEY }} ${{ secrets.VIN1 }})
        echo $car1_value
    - name: Get CX-5 value
      run: |
        car2_value=$(node get_car_value.js ${{ secrets.CAR_API_KEY }} ${{ secrets.VIN2 }})
        echo $car2_value
