name: Property Taxes

on:
  schedule:
  # Jan 1, July 1
  - cron: '0 0 1 1,4,6,9 *'
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      ROUTING_NUMBER: ${{ secrets.ROUTING_NUMBER }}
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      STREET_ADDRESS: '${{ secrets.STREET_ADDRESS }}'
      CITY: '${{ secrets.CITY }}'
      ZIP_CODE: ${{ secrets.ZIP_CODE }}
      EMAIL: ${{ secrets.EMAIL_ADDRESS }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm i
    - name: Pay property tax
      run: node pay_prop_tax.js
    - uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        path: video/*
