name: Swap to Production
on:
  workflow_dispatch:
  
jobs:
  swap:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az functionapp deployment slot swap -g ynab-sync-rg -n ynab-sync --slot rc --target-slot production
